# Generated by Django 6.0.3 on 2026-04-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_parent_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='students', to='accounts.parent'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
