# Generated by Django 6.0.3 on 2026-04-22 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('batch', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent')], max_length=10)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('nic_number', models.CharField(blank=True, max_length=20, null=True)),
                ('nic_copy', models.ImageField(blank=True, null=True, upload_to='nic/')),
                ('is_nic_verified', models.BooleanField(default=False)),
                ('is_contact_verified', models.BooleanField(default=False)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('student_age', models.IntegerField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('current_stage', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEW', 'Under Review'), ('INTERVIEW', 'Interview'), ('FINAL', 'Final Decision')], default='SUBMITTED', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('parent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_parent_accounts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ALResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=5)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='al_results', to='enrollment.enrollmentinquiry')),
            ],
        ),
        migrations.CreateModel(
            name='OLResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=5)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ol_results', to='enrollment.enrollmentinquiry')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='ACTIVE', max_length=20)),
                ('current_stage', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEW', 'Under Review'), ('INTERVIEW', 'Interview'), ('FINAL', 'Final Decision')], default='SUBMITTED', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='batch.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'batch'), name='unique_student_batch')],
            },
        ),
        migrations.AddConstraint(
            model_name='enrollmentinquiry',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_application'),
        ),
    ]
