# Generated by Django 6.0.3 on 2026-04-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_rename_message_enrollmentinquiry_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentinquiry',
            name='notes',
        ),
        migrations.AddField(
            model_name='enrollmentinquiry',
            name='role_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollmentinquiry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
