# Generated by Django 6.0.3 on 2026-04-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_remove_enrollmentinquiry_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentinquiry',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
