# Generated by Django 6.0.3 on 2026-04-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_parent_student_student_parents_and_more'),
        ('batch', '0002_remove_moduleplan_batch_remove_moduleplan_module_and_more'),
        ('enrollment', '0006_enrollmentinquiry_notes_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'batch'), name='unique_student_batch'),
        ),
    ]
