# Generated by Django 6.0.3 on 2026-04-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0007_enrollment_unique_student_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentinquiry',
            name='is_contact_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollmentinquiry',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollmentinquiry',
            name='is_nic_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollmentinquiry',
            name='nic_copy',
            field=models.ImageField(blank=True, null=True, upload_to='nic/'),
        ),
        migrations.AddField(
            model_name='enrollmentinquiry',
            name='nic_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentinquiry',
            name='risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
