# Generated by Django 6.0.3 on 2026-04-19 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollment', '0009_enrollmentinquiry_current_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ALResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='OLResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentinquiry',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='enrollmentinquiry',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_application'),
        ),
        migrations.AddField(
            model_name='alresult',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='al_results', to='enrollment.enrollmentinquiry'),
        ),
        migrations.AddField(
            model_name='olresult',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ol_results', to='enrollment.enrollmentinquiry'),
        ),
    ]
