# Generated by Django 6.0.3 on 2026-04-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0010_alresult_olresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentinquiry',
            name='address',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='current_stage',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEW', 'Under Review'), ('INTERVIEW', 'Interview'), ('FINAL', 'Final Decision')], default='SUBMITTED', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentinquiry',
            name='current_stage',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEW', 'Under Review'), ('INTERVIEW', 'Interview'), ('FINAL', 'Final Decision')], default='SUBMITTED', max_length=20),
        ),
    ]
