"""
Django settings for mit_tms project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=Csv())

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Application definition

# core/settings.py

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
LOCAL_APPS = [
    'apps.courses.apps.CoursesConfig',
    'apps.core.apps.CoreConfig',
    'apps.website.apps.WebsiteConfig',
    'apps.accounts.apps.AccountsConfig',   # ✅ ADD THIS
    'apps.batch.apps.BatchConfig',
     'apps.scheduling.apps.SchedulingConfig',
    'apps.enrollment.apps.EnrollmentConfig',
    'apps.lessonplan.apps.LessonplanConfig',
    'apps.careers.apps.CareersConfig',
    'apps.dashboard.apps.DashboardConfig',
]

THIRD_PARTY_APPS = [
    # 'rest_framework',
    # 'corsheaders',
      'django.contrib.sites',   # ✅ REQUIRED

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
        'widget_tweaks',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'allauth.account.middleware.AccountMiddleware',  # ✅ MOVE HERE

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mit_tms.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # ✅ YOUR CUSTOM
                'apps.core.context_processors.user_roles',
                'apps.core.context_processors.sidebar_menu',
            ],
        },
    },
]

WSGI_APPLICATION = 'mit_tms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


SITE_ID = 1
# ===============================
# STATIC & MEDIA FILES
# ===============================

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'


MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

# ===============================
# AUTH (FINAL CLEAN VERSION)
# ===============================
LOGIN_URL = '/accounts/login/'

LOGIN_REDIRECT_URL = '/app/dashboard/'
ACCOUNT_LOGIN_REDIRECT_URL = '/app/dashboard/'

LOGOUT_REDIRECT_URL = '/'

# 🔥 REQUIRED (fixes your error)
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'

# 🔥 New allauth format (ONLY these — no old ones)
ACCOUNT_LOGIN_METHODS = {'email', 'username'}

ACCOUNT_SIGNUP_FIELDS = [

    'email*',

]

# 🔥 Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
ACCOUNT_UNIQUE_EMAIL = True


# ===============================
# GOOGLE LOGIN
# ===============================
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_QUERY_EMAIL = True

ACCOUNT_ADAPTER = 'apps.accounts.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'apps.accounts.adapters.MySocialAccountAdapter'

OPENAI_API_KEY = config('OPENAI_API_KEY', default='')

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
