# Generated by Django 6.0.3 on 2026-04-22 13:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('entry_qualification', models.CharField(blank=True, choices=[('UPTO_OL', 'Upto O/L'), ('AL', 'A/L'), ('DIPLOMA', 'Diploma'), ('DEGREE', 'Degree')], max_length=20)),
                ('curriculum_category', models.CharField(choices=[('NVQ', 'NVQ'), ('NON_NVQ', 'Non-NVQ')], default='NON_NVQ', max_length=20)),
                ('curriculum_availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
                ('equivalent_course', models.CharField(blank=True, max_length=100)),
                ('industry_sector', models.CharField(blank=True, max_length=255)),
                ('delivery_mode', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('ONLINE', 'Online'), ('BLENDED', 'Blended')], default='CLASSROOM', max_length=20)),
                ('course_mode', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time')], default='PART_TIME', max_length=20)),
                ('medium', models.CharField(choices=[('SINHALA', 'Sinhala'), ('ENGLISH', 'English'), ('TAMIL', 'Tamil')], default='SINHALA', max_length=20)),
                ('duration_months', models.PositiveIntegerField(default=0)),
                ('theory_hours', models.FloatField(default=0)),
                ('practical_hours', models.FloatField(default=0)),
                ('assignment_hours', models.FloatField(default=0)),
                ('ojt_months', models.FloatField(default=0)),
                ('batches_per_year', models.IntegerField(default=1)),
                ('students_per_batch', models.IntegerField(default=0)),
                ('course_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('fee_includes', models.CharField(blank=True, help_text='e.g. registration, certification', max_length=255)),
                ('tools_available', models.TextField(blank=True)),
                ('equipment_available', models.TextField(blank=True)),
                ('machinery_available', models.TextField(blank=True)),
                ('nvq_level', models.IntegerField(blank=True, null=True)),
                ('qualification_code', models.CharField(blank=True, max_length=50)),
                ('prerequisite', models.TextField(blank=True)),
                ('learning_outcomes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('sector', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('module_type', models.CharField(choices=[('CORE', 'Core Module'), ('ELECTIVE', 'Elective Module'), ('BASIC', 'Basic Module')], max_length=20)),
                ('duration_months', models.PositiveIntegerField(default=0)),
                ('total_hours', models.FloatField(default=0)),
                ('theory_hours', models.FloatField(default=0)),
                ('practical_hours', models.FloatField(default=0)),
                ('learning_outcomes', models.TextField(help_text='Write outcomes as bullet points')),
                ('theory_content', models.TextField(blank=True)),
                ('practical_content', models.TextField(blank=True)),
                ('teaching_methods', models.TextField(blank=True)),
                ('assessment_methods', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='ncs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.ncs'),
        ),
        migrations.CreateModel(
            name='PerformanceCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='courses.element')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_hours', models.PositiveIntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.module')),
                ('ncs_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='courses.element')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('module', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('VIDEO', 'Video'), ('PDF', 'PDF'), ('LINK', 'External Link'), ('DOC', 'Document'), ('IMAGE', 'Image')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.module')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.task')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('FORMATIVE', 'Formative'), ('SUMMATIVE', 'Summative'), ('PROJECT', 'Project')], max_length=20)),
                ('max_marks', models.PositiveIntegerField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.course')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_assessments', to='courses.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('EXERCISE', 'Exercise'), ('ASSIGNMENT', 'Assignment'), ('MCQ', 'MCQ'), ('PRACTICAL', 'Practical'), ('DISCUSSION', 'Discussion')], default='EXERCISE', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courses.task')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_unit', to='courses.course')),
                ('ncs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nsc_unit', to='courses.ncs')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('ncs', 'code')},
            },
        ),
        migrations.AddField(
            model_name='module',
            name='ncs_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='courses.unit'),
        ),
        migrations.AddField(
            model_name='element',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='courses.unit'),
        ),
        migrations.CreateModel(
            name='StudentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('competency_achieved', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('completed_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'task'), name='unique_student_task')],
            },
        ),
        migrations.CreateModel(
            name='TaskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('FORMATIVE', 'Formative'), ('SUMMATIVE', 'Summative')], default='FORMATIVE', max_length=20)),
                ('max_marks', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assessments', to='courses.task')),
            ],
            options={
                'ordering': ['order', 'title'],
                'unique_together': {('task', 'title')},
            },
        ),
        migrations.CreateModel(
            name='TaskStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='courses.task')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('task', 'description')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='element',
            unique_together={('unit', 'title')},
        ),
    ]
