# Generated by Django 6.0.3 on 2026-04-07 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('entry_qualification', models.CharField(blank=True, choices=[('UPTO_OL', 'Upto O/L'), ('AL', 'A/L'), ('DIPLOMA', 'Diploma'), ('DEGREE', 'Degree')], max_length=20)),
                ('curriculum_category', models.CharField(choices=[('NVQ', 'NVQ'), ('NON_NVQ', 'Non-NVQ')], default='NON_NVQ', max_length=20)),
                ('curriculum_availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
                ('equivalent_course', models.CharField(blank=True, max_length=100)),
                ('industry_sector', models.CharField(blank=True, max_length=255)),
                ('delivery_mode', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('ONLINE', 'Online'), ('BLENDED', 'Blended')], default='CLASSROOM', max_length=20)),
                ('course_mode', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time')], default='PART_TIME', max_length=20)),
                ('medium', models.CharField(choices=[('SINHALA', 'Sinhala'), ('ENGLISH', 'English'), ('TAMIL', 'Tamil')], default='SINHALA', max_length=20)),
                ('duration_months', models.FloatField(default=0)),
                ('theory_hours', models.FloatField(default=0)),
                ('practical_hours', models.FloatField(default=0)),
                ('assignment_hours', models.FloatField(default=0)),
                ('ojt_months', models.FloatField(default=0)),
                ('batches_per_year', models.IntegerField(default=1)),
                ('students_per_batch', models.IntegerField(default=0)),
                ('course_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('fee_includes', models.CharField(blank=True, help_text='e.g. registration, certification', max_length=255)),
                ('tools_available', models.TextField(blank=True)),
                ('equipment_available', models.TextField(blank=True)),
                ('machinery_available', models.TextField(blank=True)),
                ('nvq_level', models.IntegerField(blank=True, null=True)),
                ('qualification_code', models.CharField(blank=True, max_length=50)),
                ('prerequisite', models.TextField(blank=True)),
                ('learning_outcomes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('TASK', 'Task'), ('MODULE', 'Module'), ('PROJECT', 'Project')], max_length=20)),
                ('max_marks', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('module_type', models.CharField(choices=[('CORE', 'Core Module'), ('ELECTIVE', 'Elective Module'), ('BASIC', 'Basic Module')], max_length=20)),
                ('total_hours', models.FloatField(default=0)),
                ('theory_hours', models.FloatField(default=0)),
                ('practical_hours', models.FloatField(default=0)),
                ('learning_outcomes', models.TextField(help_text='Write outcomes as bullet points')),
                ('theory_content', models.TextField(blank=True)),
                ('practical_content', models.TextField(blank=True)),
                ('teaching_methods', models.TextField(blank=True)),
                ('assessment_methods', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='courses.element')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration_hours', models.FloatField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField()),
                ('type', models.CharField(choices=[('EXERCISE', 'Exercise'), ('ASSIGNMENT', 'Assignment'), ('MCQ', 'MCQ'), ('PRACTICAL', 'Practical'), ('DISCUSSION', 'Discussion')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courses.task')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('FORMATIVE', 'Formative'), ('SUMMATIVE', 'Summative')], max_length=20)),
                ('max_marks', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='courses.task')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('level', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.course')),
            ],
            options={
                'unique_together': {('course', 'code')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.unit'),
        ),
        migrations.AddField(
            model_name='element',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='courses.unit'),
        ),
        migrations.CreateModel(
            name='StudentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('competency_achieved', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.task')),
            ],
            options={
                'unique_together': {('student', 'task')},
            },
        ),
    ]
