# Generated by Django 6.0.3 on 2026-04-05 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'code']},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='module',
            name='assessment_methods',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='learning_outcomes',
            field=models.TextField(default=1, help_text='Write outcomes as bullet points'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('CORE', 'Core Module'), ('ELECTIVE', 'Elective Module'), ('BASIC', 'Basic Module')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='practical_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='practical_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='teaching_methods',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='theory_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='theory_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
