# Generated by Django 6.0.3 on 2026-04-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('EXERCISE', 'Exercise'), ('ASSIGNMENT', 'Assignment'), ('MCQ', 'MCQ'), ('PRACTICAL', 'Practical'), ('DISCUSSION', 'Discussion')], default='EXERCISE', max_length=20),
        ),
    ]
