# Generated by Django 6.0.3 on 2026-04-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='industry_sector',
        ),
        migrations.AddField(
            model_name='course',
            name='industry',
            field=models.CharField(choices=[('A', 'Agriculture, Hunting and Forestry'), ('B', 'Fishing'), ('BCS', 'Common'), ('C', 'Mining and Quarrying'), ('D', 'Manufacturing'), ('E', 'Electricity, Gas and Water Supply'), ('F', 'Construction'), ('G', 'Wholesale and Retail Trade'), ('H', 'Hotel and Restaurants'), ('I', 'Transport, Storage and Communications'), ('J', 'Financial Intermediation'), ('K', 'Real Estate, Renting and Business Activities'), ('L', 'Public Administration and Defense'), ('M', 'Education'), ('N', 'Health and Social Work'), ('O', 'Other Community, Social and Personal Service Activities'), ('P', 'Private Households with Employed Persons'), ('Q', 'Extra-Territorial Organizations and Bodies')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
