# Generated by Django 6.0.3 on 2026-04-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_module_options_alter_module_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='industry_training_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='practical_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='theory_hours',
            field=models.FloatField(default=0),
        ),
    ]
