# Generated by Django 6.0.3 on 2026-04-22 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_industry_sector_course_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('TOOL', 'Tool'), ('EQUIPMENT', 'Equipment'), ('MACHINE', 'Machinery'), ('FACILITY', 'Facility')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('VIDEO', 'Video'), ('PDF', 'PDF'), ('LINK', 'External Link'), ('DOC', 'Document'), ('IMAGE', 'Image')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resources', to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='courses_linked', to='courses.learningresource'),
        ),
        migrations.AddField(
            model_name='course',
            name='physical_resources',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.physicalresource'),
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
