# Generated by Django 6.0.3 on 2026-04-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_industry_training_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration_hours',
        ),
        migrations.AddField(
            model_name='course',
            name='course_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_months',
            field=models.FloatField(default=0),
        ),
    ]
