# Generated by Django 6.0.3 on 2026-04-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_physicalresource_learningresource_course_resources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='active',
        ),
    ]
