# Generated by Django 6.0.3 on 2026-04-23 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='ncs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.ncs'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('ncs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='courses.ncs')),
            ],
        ),
    ]
