# Generated by Django 6.0.3 on 2026-04-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_unit_course_alter_unit_ncs_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='learning_resources',
            field=models.ManyToManyField(blank=True, to='courses.learningresource'),
        ),
        migrations.AddField(
            model_name='activity',
            name='method',
            field=models.CharField(blank=True, choices=[('LECTURE', 'Lecture'), ('DEMO', 'Demonstration'), ('DISCUSSION', 'Discussion'), ('PRACTICAL', 'Practical'), ('GROUP', 'Group Work')], max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='physical_resources',
            field=models.ManyToManyField(blank=True, to='courses.physicalresource'),
        ),
    ]
