# Generated by Django 6.0.3 on 2026-04-28 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_activity_learning_resources_activity_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='learning_resources',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='method',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='physical_resources',
        ),
    ]
