# Generated by Django 6.0.3 on 2026-04-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_activity_learning_resources_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studenttask',
            name='unique_student_task',
        ),
        migrations.AddField(
            model_name='assessment',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
