# Generated by Django 6.0.3 on 2026-04-29 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_studenttask_unique_student_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='bloom_level',
            field=models.CharField(blank=True, choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='code',
            field=models.CharField(blank=True, help_text='Optional short code for reporting/analytics', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='domain',
            field=models.CharField(blank=True, choices=[('cognitive', 'Cognitive'), ('psychomotor', 'Psychomotor'), ('affective', 'Affective')], max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('task', 'order')},
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['task', 'type'], name='courses_act_task_id_97d903_idx'),
        ),
    ]
