# Generated by Django 6.0.3 on 2026-04-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_activity_bloom_level_activity_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
