# Generated by Django 6.0.3 on 2026-04-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_element_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='ncs_unit',
        ),
    ]
