# Generated by Django 6.0.3 on 2026-05-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='physical_resources',
        ),
        migrations.RemoveField(
            model_name='course',
            name='resources',
        ),
    ]
