# Generated by Django 6.0.3 on 2026-05-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_course_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='industry',
        ),
    ]
