# Generated by Django 5.2.13 on 2026-05-04 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_attitude_criticalaspect_knowledge_rangestatement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='unit',
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='ncs',
            options={'ordering': ['level', 'code']},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='performancecriteria',
            options={'ordering': ['code']},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('package', 'code')},
        ),
        migrations.AddField(
            model_name='criticalaspect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='criticalaspect',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='performancecriteria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='performancecriteria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rangestatement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rangestatement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='credit_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ncs',
            name='code',
            field=models.CharField(max_length=50, unique=True,null=True),
        ),
        migrations.AlterField(
            model_name='ncs',
            name='level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ncs',
            name='sector',
            field=models.CharField(choices=[('A', 'Agriculture'), ('B', 'Fishing'), ('C', 'Mining'), ('D', 'Manufacturing'), ('E', 'Electricity'), ('F', 'Construction'), ('G', 'Trade'), ('H', 'Hospitality'), ('I', 'Transport'), ('J', 'Finance'), ('K', 'Business Services'), ('L', 'Public Administration'), ('M', 'Education'), ('N', 'Health'), ('O', 'Community Services')], max_length=5),
        ),
        migrations.AlterField(
            model_name='ncs',
            name='version',
            field=models.CharField(max_length=20,null=True),
        ),
        migrations.AlterField(
            model_name='rangestatement',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='range_statement', to='courses.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
    model_name='performancecriteria',
    name='code',
    field=models.CharField(max_length=10, null=True),
),
        migrations.AlterUniqueTogether(
            name='performancecriteria',
            unique_together={('element', 'code')},
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('domain_type', models.CharField(choices=[('K', 'Knowledge'), ('S', 'Skill'), ('A', 'Attitude')], max_length=1)),
                ('bloom_level', models.CharField(blank=True, choices=[('R', 'Remember'), ('U', 'Understand'), ('AP', 'Apply'), ('AN', 'Analyze'), ('E', 'Evaluate'), ('C', 'Create')], max_length=3, null=True)),
                ('affective_level', models.CharField(blank=True, choices=[('RE', 'Receiving'), ('RS', 'Responding'), ('VA', 'Valuing'), ('OR', 'Organizing'), ('CH', 'Characterizing')], max_length=3, null=True)),
                ('psychomotor_level', models.CharField(blank=True, choices=[('P1', 'Perception'), ('P2', 'Set'), ('P3', 'Guided Response'), ('P4', 'Mechanism'), ('P5', 'Complex Overt Response'), ('P6', 'Adaptation'), ('P7', 'Origination')], max_length=3, null=True)),
                ('description', models.TextField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='courses.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Attitude',
        ),
        migrations.DeleteModel(
            name='Knowledge',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
