# Generated by Django 5.2.13 on 2026-05-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_knowledge_unit_remove_skill_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assignment_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='ojt_months',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='practical_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='course',
            name='theory_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ncs',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='performancecriteria',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
