# Generated by Django 5.2.13 on 2026-05-04 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_course_assignment_hours_alter_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncs',
            name='version',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
