# Generated by Django 6.0.3 on 2026-04-15 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_parent_student_student_parents_and_more'),
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleplan',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='moduleplan',
            name='module',
        ),
        migrations.RemoveField(
            model_name='session',
            name='timetable',
        ),
        migrations.RemoveConstraint(
            model_name='timetable',
            name='unique_batch_day_slot',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='max_students',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='days_per_week',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='hours_per_day',
        ),
        migrations.AddField(
            model_name='batch',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='accounts.teacher'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ModulePlan',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='module',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='slot',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
