# Generated by Django 6.0.2 on 2026-04-06 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
        ('courses', '0004_remove_course_duration_hours_course_course_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('theory_hours', models.FloatField(default=0)),
                ('practical_hours', models.FloatField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='batch.batch')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module')),
            ],
        ),
    ]
