# Generated by Django 6.0.2 on 2026-04-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_moduleplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['week', 'day', 'row_slot']},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('batch', 'week', 'day', 'row_slot')},
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='row_slot',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='session_type',
        ),
    ]
