# Generated by Django 6.0.2 on 2026-04-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_alter_timetable_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.IntegerField()),
                ('is_break', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='hours',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='timetable',
            name='session_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical')], default='THEORY', max_length=10),
        ),
    ]
