# Generated by Django 6.0.2 on 2026-04-06 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_timeslot_alter_timetable_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='batch.timeslot'),
            preserve_default=False,
        ),
    ]
