# Generated by Django 6.0.3 on 2026-04-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('website', '0005_enrollment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='EnrollmentInquiry',
        ),
    ]
