# Generated by Django 6.0.3 on 2026-04-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_enrollment_enrollmentinquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnrollmentInquiry',
        ),
    ]
