# Generated by Django 6.0.3 on 2026-04-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_studentprofile_company_user_alter_application_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='training',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
