# Generated by Django 6.0.3 on 2026-04-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_activity_learning_resources_and_more'),
        ('lessonplan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonactivity',
            name='resources',
        ),
        migrations.AddField(
            model_name='lessonactivity',
            name='learning_resources',
            field=models.ManyToManyField(blank=True, to='courses.learningresource'),
        ),
        migrations.AddField(
            model_name='lessonactivity',
            name='physical_resources',
            field=models.ManyToManyField(blank=True, to='courses.physicalresource'),
        ),
        migrations.AlterField(
            model_name='lessonactivity',
            name='method',
            field=models.CharField(blank=True, choices=[('LECTURE', 'Lecture'), ('DEMO', 'Demonstration'), ('DISCUSSION', 'Discussion'), ('PRACTICAL', 'Practical'), ('GROUP', 'Group Work')], max_length=20),
        ),
    ]
