# Generated by Django 6.0.3 on 2026-04-20 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_parent_student_student_parents_and_more'),
        ('lessonplan', '0002_lessonsession_lessonperformance_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsession',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacher'),
        ),
    ]
