# Generated by Django 6.0.3 on 2026-04-29 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
        ('lessonplan', '0002_remove_lessonactivity_resources_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsession',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='batch.batch'),
        ),
    ]
