# Generated by Django 6.0.3 on 2026-04-29 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
        ('lessonplan', '0003_alter_lessonsession_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsession',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_sessions', to='batch.batch'),
        ),
        migrations.AlterField(
            model_name='lessonsession',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_sessions', to='lessonplan.lessonplan'),
        ),
    ]
