# Generated by Django 6.0.3 on 2026-04-20 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_parent_student_student_parents_and_more'),
        ('courses', '0001_initial'),
        ('lessonplan', '0003_alter_lessonsession_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='module',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='accounts.teacher'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='courses.task'),
        ),
    ]
