# Generated by Django 6.0.3 on 2026-04-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplan', '0004_remove_lessonplan_course_remove_lessonplan_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonactivity',
            name='duration_minutes',
            field=models.PositiveIntegerField(),
        ),
    ]
