# Generated by Django 6.0.3 on 2026-04-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplan', '0005_alter_lessonactivity_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('updated', 'Updated')], default='draft', max_length=20),
        ),
    ]
