# Generated by Django 6.0.3 on 2026-04-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplan', '0006_lessonplan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonactivity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='lessonactivity',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='lessonactivity',
            name='method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lessonactivity',
            name='resources',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonactivity',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonactivity',
            name='total_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonactivity',
            name='trainee_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonactivity',
            name='trainee_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonactivity',
            name='trainer_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonactivity',
            name='trainer_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='affective',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='cognitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='psychomotor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lessonperformance',
            name='understanding_level',
            field=models.IntegerField(help_text='1-5'),
        ),
    ]
